
default_context:
    bitbucket_repo: "eyed3"
    bitbucket_url: "https://bitbucket.org/bitbucket-user/eyed3"
    bitbucket_username: "bitbucket-user"
    default_locale: "en_US"
    email: "travis@pobox.com"
    full_name: "Travis Shirk"
    gettext_domain: "None"
    github_repo: "eyeD3"
    github_url: "https://github.com/nicfit/eyeD3"
    github_username: "nicfit"
    intended_audience: "Developers"
    license: "GNU GPL v3.0"
    project_long_description: ""
    project_name: "eyeD3"
    project_short_description: "Python audio data toolkit (ID3 and MP3)"
    project_slug: "eyed3"
    py26: "no"
    py27: "yes"
    py33: "no"
    py34: "yes"
    py35: "yes"
    py36: "yes"
    py37: "yes"
    py_module: "eyed3"
    pyapp_type: "normal"
    pypi_repo_name: "eyeD3"
    pypi_username: "nicfit"
    pypy: "yes"
    pypy3: "yes"
    release_date: "today"
    src_dir: "./src"
    use_bitbucket: "no"
    use_github: "yes"
    use_make: "yes"
    use_paver: "no"
    use_pypi_deployment_with_travis: "no"
    use_pytest: "yes"
    use_rtd: "no"
    use_travis_ci: "yes"
    version: "0.8.0-a5"
    web: "http://eyed3.nicfit.net/"
    year: "2002-2017"
    add_docs: "yes"
    requirements_yaml: "yes"
