# -*- coding: utf-8 -*-
"""
~~~~~~~~~~ DO NOT EDIT THIS FILE! Autogenerated by `regarding` ~~~~~~~~~~
https://github.com/nicfit/regarding
"""
import dataclasses


@dataclasses.dataclass
class Version:
    major: int
    minor: int
    maint: int
    release: str
    release_name: str


project_name = "eyeD3"
version = "0.10.0a0"
release_name = "True Blue"
author = "Travis Shirk"
author_email = "travis@pobox.com"
years = "2002-2020"
version_info = Version(
    0, 10, 0,
    "a0", "True Blue"
)
description = "Python audio data toolkit (ID3 and MP3)"
homepage = ""
