"""
~~~~~~~~~~ DO NOT EDIT THIS FILE! Autogenerated by `regarding` ~~~~~~~~~~
https://github.com/nicfit/regarding
"""
import dataclasses
from typing import Optional


__all__ = ["project_name", "version", "version_info",
           "author", "author_email", "years", "description", "homepage"]


@dataclasses.dataclass
class Version:
    major: int
    minor: int
    micro: int
    dev: Optional[int]
    pre: Optional[tuple[str, int]]
    post: Optional[int]
    release_name: Optional[str]


project_name = "eyeD3"
version = "0.9.9"
version_info = Version(
    0, 9, 9,
    None,
    None,
    None,
    "Guilty Conscience",
)

author = "Travis Shirk"
author_email = "travis@pobox.com"
years = "2002-2025"
description = "Python audio data toolkit (ID3 and MP3)"
homepage = "https://eyed3.readthedocs.io/"


def versionBanner() -> str:
    """Return the version string including release name."""
    v = ""
    if version:
        v = version
        if version_info is not None and version_info.release_name:
            v = "%s (%s)" % (v, version_info.release_name)
    return v
