main:
    - python-magic
    - dataclasses; python_version < "3.7"

extra_display-plugin:
    - grako

extra_art-plugin:
    - pylast
    - requests
    - pillow

test:
    - pytest
    - pytest-cov
    - pytest-runner
    - factory-boy

dev:
    - nicfit.py[cookiecutter]
    - Sphinx
    - sphinx_rtd_theme
    - check-manifest
    - flake8
    - ipdb
    - tox
    - twine
    - wheel
    - pyaml
    - pss
    - sphinx-issues
    # Upstream PR: https://bitbucket.org/dhellmann/sphinxcontrib-bitbucket/pull-requests/1/use-setuptools-over-distribute-python3/diff
    #- sphinxcontrib-bitbucket
    - hg+https://nicfit@bitbucket.org/nicfit/sphinxcontrib-bitbucket
    #- git+https://github.com/nicfit/gitchangelog.git
