main:
    - six
    - pathlib; python_version < '3.4'
    - python-magic

extra_display-plugin:
    - grako

extra_art-plugin:
    - pylast ~= 2.0
    - requests
    - pillow

test:
    - pytest
    - pytest-cov
    - pytest-runner
    - factory-boy
    - mock; python_version < '3.4'

dev:
    - nicfit.py[cookiecutter]
    - Sphinx
    - sphinx_rtd_theme
    - check-manifest
    - flake8
    - ipdb
    - pip-tools
    - tox
    - twine
    - wheel
    - cogapp
    - sphinxcontrib-paverutils
    - pyaml
    - pss
    - sphinx-issues
    # Upstream PR: https://bitbucket.org/dhellmann/sphinxcontrib-bitbucket/pull-requests/1/use-setuptools-over-distribute-python3/diff
    #- sphinxcontrib-bitbucket
    - hg+https://nicfit@bitbucket.org/nicfit/sphinxcontrib-bitbucket
    #- git+https://github.com/nicfit/gitchangelog.git
